### ISSUE TITLE
All settings are repeated multiple times

### ISSUE THREAD

**Issue by montemartin** [Rooyca/doing#2]
When I try to edit the settings there are only two options, but they are each repeated 8 times. See the attached screenshot.

![CleanShot 2024-07-02 at 16 51 38@2x](https://github.com/Rooyca/doing/assets/6987789/3df220a6-ee6e-4017-b84c-4e1fd4fed14d)

**Comment by Rooyca** [comment]
I forgot to add literally one line :smile:. It sould be fixed in the next update.
Thanks for pointing it out.

**Comment by Rooyca** [comment]
This should be fix by now.
